### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 1806336
video_max_pixels: 16384
trust_remote_code: true
use_fast_tokenizer: false

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: agentnet_ubuntu_5k_train  # video: mllm_video_demo
template: qwen2_vl
cutoff_len: 16384 # 4096
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2_5vl-7b/lora/sft_cua
logging_steps: 1
save_steps: 10
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1 # 1 # 2 # 4 # NOTE: Batch size > 1 OOM 
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 20
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null # /local/scratch/lin.3976/LLaMA-Factory/saves/qwen2_5vl-7b/lora/sft_cua/checkpoint-80

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
